Source/Models/ErrorViewModel.cs
namespace Source.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Source/Models/PlanetModel.cs
namespace Source.Models {
    public class PlanetModel {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public string? ImageUrl {  get; set; }
    }
}

Source/Models/ProductModel.cs
namespace Source.Models {
    public class ProductModel {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
    }
}

Source/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Source.Models;
using System.Diagnostics;

namespace Source.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Source/Controllers/PlanetController.cs
using Microsoft.AspNetCore.Mvc;
using Source.Models;
using Source.Services;

namespace Source.Controllers {
    public class PlanetController : Controller {
        private readonly ILogger<PlanetController> _logger;
        private readonly PlanetService _planetService;

        public PlanetController(ILogger<PlanetController> logger, PlanetService planetService) {
            _logger = logger;
            _planetService = planetService;
        }

        [Route("ListOfPlanets")]
        public IActionResult Index() {
            return View();
        }

        [Route("PlanetDetail/{id:int}")]
        public IActionResult Detail(int id) {
            var planetModel = _planetService
                .Where(planet => planet.Id == id)
                .FirstOrDefault();
            return View(planetModel);
        }

        [HttpGet("PlanetDetail/{name}")]
        public IActionResult Detail(string name) {
            var planetModel = _planetService
                .Where(planet => planet.Name == name)
                .FirstOrDefault();
            return View(planetModel);
        }
    }
}

Source/Controllers/SubHomeController.cs
using Microsoft.AspNetCore.Mvc;
using Source.Services;

namespace Source.Controllers {
    public class SubHomeController : Controller {
        private readonly ILogger<SubHomeController> _logger;
        private readonly ProductService _productServices;

        public SubHomeController(ILogger<SubHomeController> logger, ProductService productServices) {
            _logger = logger;
            _productServices = productServices;
        }

        public string Message() {
            _logger.LogInformation("Print infor: SubHomeController.Message()");
            _logger.LogWarning("Print warn: SubHomeController.Message()");
            _logger.LogError("Print error: SubHomeController.Message()");
            _logger.LogCritical("Print critical: SubHomeController.Message()");

            return "This is 'Message' method of SubHomeController class";
        }

        public void Nothing() {
            _logger.LogInformation("Nothing action");
            Response.Headers.Append("NothingMessage", "You can't see me");
        }

        public object Anything() {
            return DateTime.Now;
        }

        public IActionResult Readme() {
            var content = @"
            Hello
            World,
            I'm
            Mike";
            return Content(content);
        }

        public IActionResult PhonePrice() {
            return Json(new {
                ProductName = "Iphone X",
                Price = 2000
            });
        }

        public IActionResult Privacy() {
            var url = Url.Action("Privacy", "Home");
            _logger.LogInformation($"Local redirect to {url}");
            return LocalRedirect(url);
        }

        public IActionResult Youtube() {
            var url = "https://www.youtube.com";
            _logger.LogInformation($"Redirect to {url}");
            return Redirect(url);
        }

        public IActionResult HelloView(string username) {
            if (string.IsNullOrEmpty(username)) {
                username = "Guest";
            }

            /*
             * Url Example: localhost/SubHome/HelloView?username=Mike
             */
            // return View("MyViews/SubHome/HelloMyView.cshtml", username);
            // return View("Hello", username);
            return View((object)username);
        }

        [TempData]
        public string StatusMessage { get; set; }

        public IActionResult Product(int? id) {
            var product = _productServices
                .Where(product => product.Id == id)
                .FirstOrDefault();

            if (product == null) {
                //TempData["StatusMessage"] = "Product not found";

                StatusMessage = "Product not found";
                return Redirect(Url.Action("Index", "Home"));
            }
            // Case 1:
            //return View(product);

            // Case 2:
            //ViewData["Product"] = product;
            //ViewData["Title"] = product.Name;
            //return View("ProductView");

            // Case 3:
            ViewBag.Product = product;
            return View("ProductView1");
        }
    }
}

Source/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<partial name="_AlertMessage" />
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Source/Views/Planet/Detail.cshtml
@model Source.Models.PlanetModel
@{
    ViewData["Title"] = @Model.Name;
}

<h1>@Model.Name</h1>

<div class="card flex-row">
    <img class="card-img w-50 h-50" src="@Model.ImageUrl" alt="@Model.Name" />
    <div class="card-body">
        <p class="card-text">
            @Model.Description
        </p>
        <a class="card-link" onclick="history.back()">
            Back to list of Planets
        </a>
    </div>
</div>

Source/Views/Planet/Index.cshtml
@inject Source.Services.PlanetService planetService
@{
    ViewData["Title"] = "List of planets";
}

<h1>List of planets in the solar system</h1>
<div class="list-group">
    @foreach (var planet in planetService) {
        <a class="list-group-item list-group-item-action"
           asp-controller="Planet"
           asp-action="Detail"
           asp-route-name="@planet.Name">
            @planet.Name
        </a>
    }
</div>

Source/Views/Shared/_AlertMessage.cshtml
@{
    var message = TempData["StatusMessage"] as string;
}

@if (!string.IsNullOrEmpty(message)) {
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @message
    </div>
}

Source/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Source</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Source.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Source</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet" asp-action="Index">Planet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Source - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Source/Views/SubHome/Hello.cshtml
@model string
@{
    Layout = "_Layout";
}

<div class="card bg-danger text-white">
    <h1 class="card-header">Hello @Model</h1>
    <div class="card-body">
        <p class="card-text">ASP is really cool~~~~</p>
    </div>
</div>

@this.Path

Source/Views/SubHome/HelloView.cshtml
@model string
@{
    Layout = "_Layout";
}

<div class="card bg-warning text-white">
    <h1 class="card-header">Hello @Model</h1>
    <div class="card-body">
        <p class="card-text">ASP is really cool~~~~</p>
    </div>
</div>

@this.Path

Source/Views/SubHome/Product.cshtml
@model Source.Models.ProductModel

<div class="card bg-white text-black">
    <h1 class="card-header">@Model.Name</h1>
    <div class="card-body">
        <p class="card-text">Price: @Model.Price</p>
    </div>
</div>

Source/Views/SubHome/ProductView.cshtml
@model Source.Models.ProductModel
@{
    var product = ViewData["Product"] as ProductModel;
}

<div class="card bg-black text-white">
    <h1 class="card-header">@product.Name</h1>
    <div class="card-body">
        <p class="card-text">Price: @product.Price</p>
    </div>
</div>

Source/Views/SubHome/ProductView1.cshtml
@model Source.Models.ProductModel
@{
    var product = ViewBag.Product;
}

<div class="card bg-black text-white">
    <h1 class="card-header">@product.Name</h1>
    <div class="card-body">
        <p class="card-text">Price: @product.Price</p>
    </div>
</div>